### ISSUE TITLE
Does anybody use "triggerObject_firedTrigger" and "triggerObject_filterIDs" ?

### ISSUE THREAD

**Issue by gitytakahas** [UZHCMS/EXOVVNtuplizerRunII#195]
I'm doing "trimming" of the code. Does anybody use 

https://github.com/UZHCMS/EXOVVNtuplizerRunII/blob/32f4eb7e9950b4d744d3f7ef984b481e03832757/Ntuplizer/plugins/TriggersNtuplizer.cc#L397-L398

If yes, let me know soon - If not, I would remove them.

**Comment by thaarres** [comment]
For what I am concerned they can be removed

**Comment by cgalloni** [comment]
I also don't use them.

**Comment by zucchett** [comment]
Never used them, too.

**Comment by gitytakahas** [comment]
Thanks for the feedback - let's then remove these variables for the next round. I will take care of this for the next PR.
