### ISSUE TITLE
Isolation variables for the leptons redundancy

### ISSUE THREAD

**Issue by cgalloni** [UZHCMS/EXOVVNtuplizerRunII#196]
Dear All,
I'm editing the Ntuplizer code to see if it can be skimmed a bit. I found that for the lepton isolation variable there is a lot of redundancy. For instance the variables used in the isolation computation are saved using the values accessed directly from the particles and the ones in the userfloat of the particles (for example  mu.photonIso mu.userfloat("photonIso") )  and they should be the same, to my knowledge.
Can we delete one of the 2?
Then the same thing applies for different kind of isolations. I think the most used are the lep_SemileptonicPFIso and lep_SemileptonicCorrPFIso from my side and maybe the mu_trackIso for the muons.
the SemileptonicPFIso means  for electrons this means iso= RhoCorrectedIso03 and  for the muons iso = (sumChargedHadronPt + std::max( 0. ,sumNeutralHadronEt + sumPhotonEt - 0.5 * sumPUPt)
I think we could remove these other ones if people don't use them :
mu_pfRhoCorrRelIso03
mu_pfRhoCorrRelIso03Boost
mu_pfRhoCorrRelIso04
mu_pfRhoCorrRelIso04Boost
mu_pfDeltaCorrRelIso
mu_pfDeltaCorrRelIsoBoost
mu_pfRelIso
mu_pfRelIsoBoost
Please let me know if I can delete them or you need some of this variables

**Comment by gitytakahas** [comment]
I agree with your proposal. Also, from my side, I don't use the variables that you listed.

**Comment by zucchett** [comment]
I also agree. Probably it's safer to keep both the rho-area and the delta beta isolation for electrons. We can get rid of all other things, except trackIso for muons (for the VH semileptonic).
