### ISSUE TITLE
Test run

### ISSUE THREAD

**Issue by gitytakahas** [UZHCMS/EXOVVNtuplizerRunII#200]
I skimmed some information from the trigger ntuplizers.
Together with modifications from Camilla and Alberto, 
I think it is very helpful now to run the test job with MC, 
and analyze which collection still occupies what amount. 

@zucchett Since you did this before, can you do this again ? 
(of course, once you get well from the sick !)

Thanks !

**Comment by zucchett** [comment]
Hi, sure, no problem!
I was planning to work on the gen particles early next week.
After that, we will have a clearer picture, and i'll re-run the test.

**Comment by zucchett** [comment]
Update: i have re-run the test by including the latest developments + the gen particle pruning. The fraction of the size occupied by Gen Particles and Trigger Objects has decreased significantly, but unfortunately the branches saved by grooming the genparticles, electrons and muons collections have been compensated by a significant increase in the number of tau branches (from 97 to 119), and more than doubled the size! Why? I thought we agreed to reduce them as many of them are not used.
Below, you can find the pie charts.

Original situation (80X_ReMiniAOD):
![before](https://user-images.githubusercontent.com/6450143/32222067-1a07c12e-be38-11e7-86cc-67dbc9a38e21.png)

New (80X_legacy):
![after](https://user-images.githubusercontent.com/6450143/32222066-19e360ea-be38-11e7-84a1-ffec1201b239.png)

**Comment by gitytakahas** [comment]
thanks - this is really helpful. 
Can you give us the absolute size as well?

**Comment by zucchett** [comment]
The "old" ntuple was 974K, the "new" one is 771K (100 events ttbar). The decrease in size is almost entirely due to the genParticles, while the savings from the Trigger Objects, Electrons, Muons are compensated by the increase in the Tau size, approximately for the same amount of disk space.

**Comment by gitytakahas** [comment]
974K x 0.091 = 88.6K
771K x 0.323 = 249K

So, it is factor 3 increase. Hmm, I think I found the reason. This commit, 

https://github.com/UZHCMS/EXOVVNtuplizerRunII/commit/c7016dd675303e61838503c2309db155adb2c2b2#diff-71fcd1a1dd472b37f7382fdf4a2c41fe

where I updated such that it saves all PF candidates around taus. Let me update this and commit again.

**Comment by gitytakahas** [comment]
I just committed and merged updates (https://github.com/UZHCMS/EXOVVNtuplizerRunII/pull/202)
Can you fetch them, compile again, and run the test again?

Thanks

**Comment by cgalloni** [comment]
Hi Yuta,
are all the PF candidates needed or can we just save some of their info?
Thanks

**Comment by gitytakahas** [comment]
Hi Camilla - I just deleted them. These were used for the tau MVA studies (spatial distributions of PF candidates around taus). It won't be needed (i hope).

**Comment by zucchett** [comment]
Hi Yuta, for now i created the PR for the genParticle pruning. Later today i'll get your latest PR and run the test again.

**Comment by gitytakahas** [comment]
OK, thanks !

**Comment by zucchett** [comment]
There is some improvement, but the size is still quite large (the last PR with the tau modifications has decreased the overall size by 14%).
There are still 114 branches with tau variables. Can we reduce them by half? Or can we apply preselections on the written taus?
![chart](https://user-images.githubusercontent.com/6450143/32235719-8b46f01c-be60-11e7-99ad-7ca1c3492974.png)

**Comment by gitytakahas** [comment]
Thanks for the check Alberto ! 

The remaining updates since before, was the inclusion of all MVA input variables, and this should be responsible for the rest of increase. I believe these new variables would be useful in the future for tau ID studies, and I don't want to delete them. 

On the other hand, there is one thing we can try -> @cgalloni can we remove all the variables related to "pw" (pileup weighted) isolation, such as "tau_byIsolationMVArun2v1PWdR03oldDMwLTraw"? This has 
not been used and should continue to be so in the future, too. This should help reducing the size, as there are many. 

I think I can also remove following variables (for which I'm the only user)
> tau_footprintCorrection 
> tau_n_h_f
> tau_n_em_f
> tau_n_e
> tau_n_mu

Please let me know,
Yuta

**Comment by cgalloni** [comment]
Hi Yuta, 
I use  the PW isolation, since they are just one float and few bools, I don't think it should change much in the size of the file. For the other variable you can comment them out if they are not needed for the TAU SF. In my analysis I don't use them.

**Comment by cgalloni** [comment]
Yesterday I also saw that some variables are defined as double.. maybe the float precision could be enough?  that should save some space

**Comment by cgalloni** [comment]
Probably this one should be  float @gitytakahas ://github.com/UZHCMS/EXOVVNtuplizerRunII/blob/80X_legacy/Ntuplizer/interface/NtupleBranches.h#L378

**Comment by gitytakahas** [comment]
@zucchett thanks for the merge- I now hope that the size will be reduced for tau collection !

**Comment by zucchett** [comment]
I think that this issue can be closed now. Below, the latest results. From the Late 2016 ntuples, weighting 2.3 MB per event, we reduced the size to about 630 kB/ev.

![chart 2](https://user-images.githubusercontent.com/6450143/32445372-d3ab810c-c305-11e7-82ff-e824e31048d5.png)
