### ISSUE TITLE
dump all trigger decisions dynamically

### ISSUE THREAD

**Issue by clelange** [UZHCMS/EXOVVNtuplizerRunII#37]
instead of defining just a few trigger decisions, loop over the available triggers in the dataset and dump them all as individual booleans

**Comment by jngadiub** [comment]
Dumped all useful triggers in a map<std::string,bool>. All the trigger version will be dumped automatically.
The same should be done for trigger objects.

**Comment by clelange** [comment]
What's wrong with just dumping all triggers? Then we won't have to worry about them at all. Of course, only for the ones we care about/really use dump the trigger objects.

**Comment by jngadiub** [comment]
Because they are hundreds and we definitely do not need all of them. I think we know already which ones are interesting for our analyses. Of course is the code is meant for other kind of final states as well then they would have to add their triggers. But I don't mind to add all of them.
