### ISSUE TITLE
use correct primary vertex

### ISSUE THREAD

**Issue by clelange** [UZHCMS/EXOVVNtuplizerRunII#38]
instead of using the first vertex (index 0), should use the first that passes quality cuts, see https://github.com/ikrav/EgammaWork/blob/ntupler_and_VID_demos/ElectronNtupler/plugins/ElectronNtuplerVIDDemo.cc#L271
This is in particular needed in the ElectronNtuplizer, but probably also in other places.

**Comment by jngadiub** [comment]
Fixed by Jennifer
